export const getLatestReleaseResponse = {
  "url": "https://api.github.com/repos/dariodumlijan/project-status/releases/120968207",
  "assets_url": "https://api.github.com/repos/dariodumlijan/project-status/releases/120968207/assets",
  "upload_url": "https://uploads.github.com/repos/dariodumlijan/project-status/releases/120968207/assets{?name,label}",
  "html_url": "https://github.com/dariodumlijan/project-status/releases/tag/v1.0.0",
  "id": 120968207,
  "author": {
    "login": "dariodumlijan",
    "id": 79607795,
    "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
    "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dariodumlijan",
    "html_url": "https://github.com/dariodumlijan",
    "followers_url": "https://api.github.com/users/dariodumlijan/followers",
    "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
    "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
    "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
    "repos_url": "https://api.github.com/users/dariodumlijan/repos",
    "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "node_id": "RE_kwDOKRtVu84HNdQP",
  "tag_name": "v1.0.0",
  "target_commitish": "main",
  "name": "v1.0.0",
  "draft": false,
  "prerelease": false,
  "created_at": "2023-09-13T13:34:30Z",
  "published_at": "2023-09-13T13:40:21Z",
  "assets": [],
  "tarball_url": "https://api.github.com/repos/dariodumlijan/project-status/tarball/v1.0.0",
  "zipball_url": "https://api.github.com/repos/dariodumlijan/project-status/zipball/v1.0.0",
  "body": "## v1.0.0\r\n\r\n##### *This is an example of release notes\r\n\r\n### ✨ New Features\r\n\r\n- Added a new feature to allow users to create custom templates.\r\n- Improved the search functionality to make it easier to find the information you need.\r\n- Added a new tutorial to help users get started with the software.\r\n\r\n### 🐞 Bug Fixes\r\n\r\n- Fixed a bug that caused the software to crash when opening a large file.\r\n- Fixed a bug that prevented users from resizing the text editor.\r\n- Fixed a bug that caused the software to display incorrect information in some cases.\r\n\r\n### 🔄 Other Changes\r\n\r\n- Updated the documentation to reflect the new changes.\r\n- Updated the code to improve performance.",
  "reactions": {
    "url": "https://api.github.com/repos/dariodumlijan/project-status/releases/120968207/reactions",
    "total_count": 1,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 1,
    "eyes": 0
  }
};

export const getIssueByNumberResponse = {
  "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/1",
  "repository_url": "https://api.github.com/repos/dariodumlijan/project-status",
  "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/1/labels{/name}",
  "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/1/comments",
  "events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/1/events",
  "html_url": "https://github.com/dariodumlijan/project-status/issues/1",
  "id": 1889258377,
  "node_id": "I_kwDOKRtVu85wm8uJ",
  "number": 1,
  "title": "Project status",
  "user": {
    "login": "dariodumlijan",
    "id": 79607795,
    "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
    "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dariodumlijan",
    "html_url": "https://github.com/dariodumlijan",
    "followers_url": "https://api.github.com/users/dariodumlijan/followers",
    "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
    "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
    "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
    "repos_url": "https://api.github.com/users/dariodumlijan/repos",
    "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "labels": [],
  "state": "closed",
  "locked": true,
  "assignee": null,
  "assignees": [],
  "milestone": null,
  "comments": 0,
  "created_at": "2023-09-10T17:30:57Z",
  "updated_at": "2025-06-15T14:08:19Z",
  "closed_at": "2023-09-12T13:26:43Z",
  "author_association": "OWNER",
  "active_lock_reason": null,
  "sub_issues_summary": {
    "total": 6,
    "completed": 6,
    "percent_completed": 100
  },
  "body": "##### *This is an example of a status report\n\n----\n\nWe are committed to providing you with the best possible experience with our software. As part of this commitment, we are constantly monitoring the software for performance issues and other bugs.\n\n### Known Issues\n\n* The software may experience occasional slowdowns when opening large files.\n* The software may crash in rare cases.\n* The software may display incorrect information in some cases.\n\n### Work in Progress\n\n* Improving the performance of the software when opening large files.\n* Fixing the bug that causes the software to crash in rare cases.\n* Fixing the bug that causes the software to display incorrect information in some cases.\n\n### We Appreciate Your Patience\n\nWe appreciate your patience as we work to resolve these issues. We will continue to provide updates on our progress.\n\nIf you experience any other issues with the software, please contact us so we can investigate.\n\nThank you for using our software!",
  "closed_by": {
    "login": "dariodumlijan",
    "id": 79607795,
    "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
    "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dariodumlijan",
    "html_url": "https://github.com/dariodumlijan",
    "followers_url": "https://api.github.com/users/dariodumlijan/followers",
    "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
    "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
    "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
    "repos_url": "https://api.github.com/users/dariodumlijan/repos",
    "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/1/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/1/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
};

export const getSubIssuesByNumberResponse = [
  {
    "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/10",
    "repository_url": "https://api.github.com/repos/dariodumlijan/project-status",
    "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/10/labels{/name}",
    "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/10/comments",
    "events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/10/events",
    "html_url": "https://github.com/dariodumlijan/project-status/issues/10",
    "id": 3147608653,
    "node_id": "I_kwDOKRtVu867nLJN",
    "number": 10,
    "title": "Web APP",
    "user": {
      "login": "dariodumlijan",
      "id": 79607795,
      "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dariodumlijan",
      "html_url": "https://github.com/dariodumlijan",
      "followers_url": "https://api.github.com/users/dariodumlijan/followers",
      "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
      "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
      "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
      "repos_url": "https://api.github.com/users/dariodumlijan/repos",
      "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 8785596900,
        "node_id": "LA_kwDOKRtVu88AAAACC6mR5A",
        "url": "https://api.github.com/repos/dariodumlijan/project-status/labels/operational",
        "name": "operational",
        "color": "22c55e",
        "default": false,
        "description": ""
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2025-06-15T14:23:27Z",
    "updated_at": "2025-06-15T14:26:10Z",
    "closed_at": "2025-06-15T14:26:10Z",
    "author_association": "OWNER",
    "active_lock_reason": null,
    "sub_issues_summary": {
      "total": 0,
      "completed": 0,
      "percent_completed": 0
    },
    "repository": {
      "id": 689657275,
      "node_id": "R_kgDOKRtVuw",
      "name": "project-status",
      "full_name": "dariodumlijan/project-status",
      "private": false,
      "owner": {
        "login": "dariodumlijan",
        "id": 79607795,
        "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
        "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dariodumlijan",
        "html_url": "https://github.com/dariodumlijan",
        "followers_url": "https://api.github.com/users/dariodumlijan/followers",
        "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
        "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
        "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
        "repos_url": "https://api.github.com/users/dariodumlijan/repos",
        "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/dariodumlijan/project-status",
      "description": "SPA (React) for displaying  project release notes & status using GitHub API",
      "fork": false,
      "url": "https://api.github.com/repos/dariodumlijan/project-status",
      "forks_url": "https://api.github.com/repos/dariodumlijan/project-status/forks",
      "keys_url": "https://api.github.com/repos/dariodumlijan/project-status/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/dariodumlijan/project-status/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/dariodumlijan/project-status/teams",
      "hooks_url": "https://api.github.com/repos/dariodumlijan/project-status/hooks",
      "issue_events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/events{/number}",
      "events_url": "https://api.github.com/repos/dariodumlijan/project-status/events",
      "assignees_url": "https://api.github.com/repos/dariodumlijan/project-status/assignees{/user}",
      "branches_url": "https://api.github.com/repos/dariodumlijan/project-status/branches{/branch}",
      "tags_url": "https://api.github.com/repos/dariodumlijan/project-status/tags",
      "blobs_url": "https://api.github.com/repos/dariodumlijan/project-status/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/dariodumlijan/project-status/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/dariodumlijan/project-status/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/dariodumlijan/project-status/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/dariodumlijan/project-status/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/dariodumlijan/project-status/languages",
      "stargazers_url": "https://api.github.com/repos/dariodumlijan/project-status/stargazers",
      "contributors_url": "https://api.github.com/repos/dariodumlijan/project-status/contributors",
      "subscribers_url": "https://api.github.com/repos/dariodumlijan/project-status/subscribers",
      "subscription_url": "https://api.github.com/repos/dariodumlijan/project-status/subscription",
      "commits_url": "https://api.github.com/repos/dariodumlijan/project-status/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/dariodumlijan/project-status/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/dariodumlijan/project-status/contents/{+path}",
      "compare_url": "https://api.github.com/repos/dariodumlijan/project-status/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/dariodumlijan/project-status/merges",
      "archive_url": "https://api.github.com/repos/dariodumlijan/project-status/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/dariodumlijan/project-status/downloads",
      "issues_url": "https://api.github.com/repos/dariodumlijan/project-status/issues{/number}",
      "pulls_url": "https://api.github.com/repos/dariodumlijan/project-status/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/dariodumlijan/project-status/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/dariodumlijan/project-status/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/labels{/name}",
      "releases_url": "https://api.github.com/repos/dariodumlijan/project-status/releases{/id}",
      "deployments_url": "https://api.github.com/repos/dariodumlijan/project-status/deployments",
      "created_at": "2023-09-10T14:04:22Z",
      "updated_at": "2024-11-13T22:22:31Z",
      "pushed_at": "2024-11-13T22:18:04Z",
      "git_url": "git://github.com/dariodumlijan/project-status.git",
      "ssh_url": "git@github.com:dariodumlijan/project-status.git",
      "clone_url": "https://github.com/dariodumlijan/project-status.git",
      "svn_url": "https://github.com/dariodumlijan/project-status",
      "homepage": "https://project-status.dariodumlijan.com",
      "size": 1649,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": true,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": true,
      "web_commit_signoff_required": false,
      "topics": [
        "github-actions",
        "github-api",
        "github-pages",
        "react",
        "react-query",
        "reactjs",
        "scss",
        "status",
        "status-page",
        "typescript",
        "vite",
        "vitejs",
        "vitejs-react",
        "vitejs-react-typescript",
        "vitejs-template"
      ],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main",
      "permissions": {
        "admin": true,
        "maintain": true,
        "push": true,
        "triage": true,
        "pull": true
      }
    },
    "body": null,
    "reactions": {
      "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/10/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/10/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
  },
  {
    "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/11",
    "repository_url": "https://api.github.com/repos/dariodumlijan/project-status",
    "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/11/labels{/name}",
    "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/11/comments",
    "events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/11/events",
    "html_url": "https://github.com/dariodumlijan/project-status/issues/11",
    "id": 3147609140,
    "node_id": "I_kwDOKRtVu867nLQ0",
    "number": 11,
    "title": "REST API",
    "user": {
      "login": "dariodumlijan",
      "id": 79607795,
      "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dariodumlijan",
      "html_url": "https://github.com/dariodumlijan",
      "followers_url": "https://api.github.com/users/dariodumlijan/followers",
      "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
      "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
      "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
      "repos_url": "https://api.github.com/users/dariodumlijan/repos",
      "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 8785615565,
        "node_id": "LA_kwDOKRtVu88AAAACC6nazQ",
        "url": "https://api.github.com/repos/dariodumlijan/project-status/labels/degraded",
        "name": "degraded",
        "color": "bf781d",
        "default": false,
        "description": ""
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2025-06-15T14:23:46Z",
    "updated_at": "2025-06-15T14:26:10Z",
    "closed_at": "2025-06-15T14:26:10Z",
    "author_association": "OWNER",
    "active_lock_reason": null,
    "sub_issues_summary": {
      "total": 0,
      "completed": 0,
      "percent_completed": 0
    },
    "repository": {
      "id": 689657275,
      "node_id": "R_kgDOKRtVuw",
      "name": "project-status",
      "full_name": "dariodumlijan/project-status",
      "private": false,
      "owner": {
        "login": "dariodumlijan",
        "id": 79607795,
        "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
        "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dariodumlijan",
        "html_url": "https://github.com/dariodumlijan",
        "followers_url": "https://api.github.com/users/dariodumlijan/followers",
        "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
        "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
        "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
        "repos_url": "https://api.github.com/users/dariodumlijan/repos",
        "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/dariodumlijan/project-status",
      "description": "SPA (React) for displaying  project release notes & status using GitHub API",
      "fork": false,
      "url": "https://api.github.com/repos/dariodumlijan/project-status",
      "forks_url": "https://api.github.com/repos/dariodumlijan/project-status/forks",
      "keys_url": "https://api.github.com/repos/dariodumlijan/project-status/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/dariodumlijan/project-status/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/dariodumlijan/project-status/teams",
      "hooks_url": "https://api.github.com/repos/dariodumlijan/project-status/hooks",
      "issue_events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/events{/number}",
      "events_url": "https://api.github.com/repos/dariodumlijan/project-status/events",
      "assignees_url": "https://api.github.com/repos/dariodumlijan/project-status/assignees{/user}",
      "branches_url": "https://api.github.com/repos/dariodumlijan/project-status/branches{/branch}",
      "tags_url": "https://api.github.com/repos/dariodumlijan/project-status/tags",
      "blobs_url": "https://api.github.com/repos/dariodumlijan/project-status/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/dariodumlijan/project-status/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/dariodumlijan/project-status/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/dariodumlijan/project-status/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/dariodumlijan/project-status/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/dariodumlijan/project-status/languages",
      "stargazers_url": "https://api.github.com/repos/dariodumlijan/project-status/stargazers",
      "contributors_url": "https://api.github.com/repos/dariodumlijan/project-status/contributors",
      "subscribers_url": "https://api.github.com/repos/dariodumlijan/project-status/subscribers",
      "subscription_url": "https://api.github.com/repos/dariodumlijan/project-status/subscription",
      "commits_url": "https://api.github.com/repos/dariodumlijan/project-status/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/dariodumlijan/project-status/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/dariodumlijan/project-status/contents/{+path}",
      "compare_url": "https://api.github.com/repos/dariodumlijan/project-status/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/dariodumlijan/project-status/merges",
      "archive_url": "https://api.github.com/repos/dariodumlijan/project-status/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/dariodumlijan/project-status/downloads",
      "issues_url": "https://api.github.com/repos/dariodumlijan/project-status/issues{/number}",
      "pulls_url": "https://api.github.com/repos/dariodumlijan/project-status/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/dariodumlijan/project-status/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/dariodumlijan/project-status/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/labels{/name}",
      "releases_url": "https://api.github.com/repos/dariodumlijan/project-status/releases{/id}",
      "deployments_url": "https://api.github.com/repos/dariodumlijan/project-status/deployments",
      "created_at": "2023-09-10T14:04:22Z",
      "updated_at": "2024-11-13T22:22:31Z",
      "pushed_at": "2024-11-13T22:18:04Z",
      "git_url": "git://github.com/dariodumlijan/project-status.git",
      "ssh_url": "git@github.com:dariodumlijan/project-status.git",
      "clone_url": "https://github.com/dariodumlijan/project-status.git",
      "svn_url": "https://github.com/dariodumlijan/project-status",
      "homepage": "https://project-status.dariodumlijan.com",
      "size": 1649,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": true,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": true,
      "web_commit_signoff_required": false,
      "topics": [
        "github-actions",
        "github-api",
        "github-pages",
        "react",
        "react-query",
        "reactjs",
        "scss",
        "status",
        "status-page",
        "typescript",
        "vite",
        "vitejs",
        "vitejs-react",
        "vitejs-react-typescript",
        "vitejs-template"
      ],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main",
      "permissions": {
        "admin": true,
        "maintain": true,
        "push": true,
        "triage": true,
        "pull": true
      }
    },
    "body": null,
    "reactions": {
      "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/11/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/11/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
  },
  {
    "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/12",
    "repository_url": "https://api.github.com/repos/dariodumlijan/project-status",
    "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/12/labels{/name}",
    "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/12/comments",
    "events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/12/events",
    "html_url": "https://github.com/dariodumlijan/project-status/issues/12",
    "id": 3147609327,
    "node_id": "I_kwDOKRtVu867nLTv",
    "number": 12,
    "title": "Database",
    "user": {
      "login": "dariodumlijan",
      "id": 79607795,
      "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dariodumlijan",
      "html_url": "https://github.com/dariodumlijan",
      "followers_url": "https://api.github.com/users/dariodumlijan/followers",
      "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
      "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
      "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
      "repos_url": "https://api.github.com/users/dariodumlijan/repos",
      "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 8785616209,
        "node_id": "LA_kwDOKRtVu88AAAACC6ndUQ",
        "url": "https://api.github.com/repos/dariodumlijan/project-status/labels/down",
        "name": "down",
        "color": "fb2c36",
        "default": false,
        "description": ""
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2025-06-15T14:24:03Z",
    "updated_at": "2025-06-15T14:26:10Z",
    "closed_at": "2025-06-15T14:26:10Z",
    "author_association": "OWNER",
    "active_lock_reason": null,
    "sub_issues_summary": {
      "total": 0,
      "completed": 0,
      "percent_completed": 0
    },
    "repository": {
      "id": 689657275,
      "node_id": "R_kgDOKRtVuw",
      "name": "project-status",
      "full_name": "dariodumlijan/project-status",
      "private": false,
      "owner": {
        "login": "dariodumlijan",
        "id": 79607795,
        "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
        "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dariodumlijan",
        "html_url": "https://github.com/dariodumlijan",
        "followers_url": "https://api.github.com/users/dariodumlijan/followers",
        "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
        "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
        "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
        "repos_url": "https://api.github.com/users/dariodumlijan/repos",
        "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/dariodumlijan/project-status",
      "description": "SPA (React) for displaying  project release notes & status using GitHub API",
      "fork": false,
      "url": "https://api.github.com/repos/dariodumlijan/project-status",
      "forks_url": "https://api.github.com/repos/dariodumlijan/project-status/forks",
      "keys_url": "https://api.github.com/repos/dariodumlijan/project-status/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/dariodumlijan/project-status/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/dariodumlijan/project-status/teams",
      "hooks_url": "https://api.github.com/repos/dariodumlijan/project-status/hooks",
      "issue_events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/events{/number}",
      "events_url": "https://api.github.com/repos/dariodumlijan/project-status/events",
      "assignees_url": "https://api.github.com/repos/dariodumlijan/project-status/assignees{/user}",
      "branches_url": "https://api.github.com/repos/dariodumlijan/project-status/branches{/branch}",
      "tags_url": "https://api.github.com/repos/dariodumlijan/project-status/tags",
      "blobs_url": "https://api.github.com/repos/dariodumlijan/project-status/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/dariodumlijan/project-status/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/dariodumlijan/project-status/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/dariodumlijan/project-status/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/dariodumlijan/project-status/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/dariodumlijan/project-status/languages",
      "stargazers_url": "https://api.github.com/repos/dariodumlijan/project-status/stargazers",
      "contributors_url": "https://api.github.com/repos/dariodumlijan/project-status/contributors",
      "subscribers_url": "https://api.github.com/repos/dariodumlijan/project-status/subscribers",
      "subscription_url": "https://api.github.com/repos/dariodumlijan/project-status/subscription",
      "commits_url": "https://api.github.com/repos/dariodumlijan/project-status/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/dariodumlijan/project-status/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/dariodumlijan/project-status/contents/{+path}",
      "compare_url": "https://api.github.com/repos/dariodumlijan/project-status/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/dariodumlijan/project-status/merges",
      "archive_url": "https://api.github.com/repos/dariodumlijan/project-status/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/dariodumlijan/project-status/downloads",
      "issues_url": "https://api.github.com/repos/dariodumlijan/project-status/issues{/number}",
      "pulls_url": "https://api.github.com/repos/dariodumlijan/project-status/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/dariodumlijan/project-status/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/dariodumlijan/project-status/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/labels{/name}",
      "releases_url": "https://api.github.com/repos/dariodumlijan/project-status/releases{/id}",
      "deployments_url": "https://api.github.com/repos/dariodumlijan/project-status/deployments",
      "created_at": "2023-09-10T14:04:22Z",
      "updated_at": "2024-11-13T22:22:31Z",
      "pushed_at": "2024-11-13T22:18:04Z",
      "git_url": "git://github.com/dariodumlijan/project-status.git",
      "ssh_url": "git@github.com:dariodumlijan/project-status.git",
      "clone_url": "https://github.com/dariodumlijan/project-status.git",
      "svn_url": "https://github.com/dariodumlijan/project-status",
      "homepage": "https://project-status.dariodumlijan.com",
      "size": 1649,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": true,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": true,
      "web_commit_signoff_required": false,
      "topics": [
        "github-actions",
        "github-api",
        "github-pages",
        "react",
        "react-query",
        "reactjs",
        "scss",
        "status",
        "status-page",
        "typescript",
        "vite",
        "vitejs",
        "vitejs-react",
        "vitejs-react-typescript",
        "vitejs-template"
      ],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main",
      "permissions": {
        "admin": true,
        "maintain": true,
        "push": true,
        "triage": true,
        "pull": true
      }
    },
    "body": null,
    "reactions": {
      "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/12/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/12/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
  },
  {
    "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/13",
    "repository_url": "https://api.github.com/repos/dariodumlijan/project-status",
    "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/13/labels{/name}",
    "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/13/comments",
    "events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/13/events",
    "html_url": "https://github.com/dariodumlijan/project-status/issues/13",
    "id": 3147609889,
    "node_id": "I_kwDOKRtVu867nLch",
    "number": 13,
    "title": "File Storage",
    "user": {
      "login": "dariodumlijan",
      "id": 79607795,
      "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dariodumlijan",
      "html_url": "https://github.com/dariodumlijan",
      "followers_url": "https://api.github.com/users/dariodumlijan/followers",
      "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
      "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
      "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
      "repos_url": "https://api.github.com/users/dariodumlijan/repos",
      "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 8785617632,
        "node_id": "LA_kwDOKRtVu88AAAACC6ni4A",
        "url": "https://api.github.com/repos/dariodumlijan/project-status/labels/recovering",
        "name": "recovering",
        "color": "00a6f4",
        "default": false,
        "description": ""
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2025-06-15T14:24:28Z",
    "updated_at": "2025-06-15T14:26:10Z",
    "closed_at": "2025-06-15T14:26:10Z",
    "author_association": "OWNER",
    "active_lock_reason": null,
    "sub_issues_summary": {
      "total": 0,
      "completed": 0,
      "percent_completed": 0
    },
    "repository": {
      "id": 689657275,
      "node_id": "R_kgDOKRtVuw",
      "name": "project-status",
      "full_name": "dariodumlijan/project-status",
      "private": false,
      "owner": {
        "login": "dariodumlijan",
        "id": 79607795,
        "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
        "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dariodumlijan",
        "html_url": "https://github.com/dariodumlijan",
        "followers_url": "https://api.github.com/users/dariodumlijan/followers",
        "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
        "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
        "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
        "repos_url": "https://api.github.com/users/dariodumlijan/repos",
        "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/dariodumlijan/project-status",
      "description": "SPA (React) for displaying  project release notes & status using GitHub API",
      "fork": false,
      "url": "https://api.github.com/repos/dariodumlijan/project-status",
      "forks_url": "https://api.github.com/repos/dariodumlijan/project-status/forks",
      "keys_url": "https://api.github.com/repos/dariodumlijan/project-status/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/dariodumlijan/project-status/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/dariodumlijan/project-status/teams",
      "hooks_url": "https://api.github.com/repos/dariodumlijan/project-status/hooks",
      "issue_events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/events{/number}",
      "events_url": "https://api.github.com/repos/dariodumlijan/project-status/events",
      "assignees_url": "https://api.github.com/repos/dariodumlijan/project-status/assignees{/user}",
      "branches_url": "https://api.github.com/repos/dariodumlijan/project-status/branches{/branch}",
      "tags_url": "https://api.github.com/repos/dariodumlijan/project-status/tags",
      "blobs_url": "https://api.github.com/repos/dariodumlijan/project-status/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/dariodumlijan/project-status/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/dariodumlijan/project-status/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/dariodumlijan/project-status/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/dariodumlijan/project-status/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/dariodumlijan/project-status/languages",
      "stargazers_url": "https://api.github.com/repos/dariodumlijan/project-status/stargazers",
      "contributors_url": "https://api.github.com/repos/dariodumlijan/project-status/contributors",
      "subscribers_url": "https://api.github.com/repos/dariodumlijan/project-status/subscribers",
      "subscription_url": "https://api.github.com/repos/dariodumlijan/project-status/subscription",
      "commits_url": "https://api.github.com/repos/dariodumlijan/project-status/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/dariodumlijan/project-status/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/dariodumlijan/project-status/contents/{+path}",
      "compare_url": "https://api.github.com/repos/dariodumlijan/project-status/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/dariodumlijan/project-status/merges",
      "archive_url": "https://api.github.com/repos/dariodumlijan/project-status/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/dariodumlijan/project-status/downloads",
      "issues_url": "https://api.github.com/repos/dariodumlijan/project-status/issues{/number}",
      "pulls_url": "https://api.github.com/repos/dariodumlijan/project-status/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/dariodumlijan/project-status/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/dariodumlijan/project-status/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/labels{/name}",
      "releases_url": "https://api.github.com/repos/dariodumlijan/project-status/releases{/id}",
      "deployments_url": "https://api.github.com/repos/dariodumlijan/project-status/deployments",
      "created_at": "2023-09-10T14:04:22Z",
      "updated_at": "2024-11-13T22:22:31Z",
      "pushed_at": "2024-11-13T22:18:04Z",
      "git_url": "git://github.com/dariodumlijan/project-status.git",
      "ssh_url": "git@github.com:dariodumlijan/project-status.git",
      "clone_url": "https://github.com/dariodumlijan/project-status.git",
      "svn_url": "https://github.com/dariodumlijan/project-status",
      "homepage": "https://project-status.dariodumlijan.com",
      "size": 1649,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": true,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": true,
      "web_commit_signoff_required": false,
      "topics": [
        "github-actions",
        "github-api",
        "github-pages",
        "react",
        "react-query",
        "reactjs",
        "scss",
        "status",
        "status-page",
        "typescript",
        "vite",
        "vitejs",
        "vitejs-react",
        "vitejs-react-typescript",
        "vitejs-template"
      ],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main",
      "permissions": {
        "admin": true,
        "maintain": true,
        "push": true,
        "triage": true,
        "pull": true
      }
    },
    "body": null,
    "reactions": {
      "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/13/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/13/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
  },
  {
    "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/14",
    "repository_url": "https://api.github.com/repos/dariodumlijan/project-status",
    "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/14/labels{/name}",
    "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/14/comments",
    "events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/14/events",
    "html_url": "https://github.com/dariodumlijan/project-status/issues/14",
    "id": 3147610606,
    "node_id": "I_kwDOKRtVu867nLnu",
    "number": 14,
    "title": "Authentication",
    "user": {
      "login": "dariodumlijan",
      "id": 79607795,
      "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dariodumlijan",
      "html_url": "https://github.com/dariodumlijan",
      "followers_url": "https://api.github.com/users/dariodumlijan/followers",
      "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
      "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
      "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
      "repos_url": "https://api.github.com/users/dariodumlijan/repos",
      "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 8785596900,
        "node_id": "LA_kwDOKRtVu88AAAACC6mR5A",
        "url": "https://api.github.com/repos/dariodumlijan/project-status/labels/operational",
        "name": "operational",
        "color": "22c55e",
        "default": false,
        "description": ""
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2025-06-15T14:25:07Z",
    "updated_at": "2025-06-15T14:26:11Z",
    "closed_at": "2025-06-15T14:26:11Z",
    "author_association": "OWNER",
    "active_lock_reason": null,
    "sub_issues_summary": {
      "total": 0,
      "completed": 0,
      "percent_completed": 0
    },
    "repository": {
      "id": 689657275,
      "node_id": "R_kgDOKRtVuw",
      "name": "project-status",
      "full_name": "dariodumlijan/project-status",
      "private": false,
      "owner": {
        "login": "dariodumlijan",
        "id": 79607795,
        "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
        "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dariodumlijan",
        "html_url": "https://github.com/dariodumlijan",
        "followers_url": "https://api.github.com/users/dariodumlijan/followers",
        "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
        "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
        "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
        "repos_url": "https://api.github.com/users/dariodumlijan/repos",
        "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/dariodumlijan/project-status",
      "description": "SPA (React) for displaying  project release notes & status using GitHub API",
      "fork": false,
      "url": "https://api.github.com/repos/dariodumlijan/project-status",
      "forks_url": "https://api.github.com/repos/dariodumlijan/project-status/forks",
      "keys_url": "https://api.github.com/repos/dariodumlijan/project-status/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/dariodumlijan/project-status/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/dariodumlijan/project-status/teams",
      "hooks_url": "https://api.github.com/repos/dariodumlijan/project-status/hooks",
      "issue_events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/events{/number}",
      "events_url": "https://api.github.com/repos/dariodumlijan/project-status/events",
      "assignees_url": "https://api.github.com/repos/dariodumlijan/project-status/assignees{/user}",
      "branches_url": "https://api.github.com/repos/dariodumlijan/project-status/branches{/branch}",
      "tags_url": "https://api.github.com/repos/dariodumlijan/project-status/tags",
      "blobs_url": "https://api.github.com/repos/dariodumlijan/project-status/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/dariodumlijan/project-status/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/dariodumlijan/project-status/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/dariodumlijan/project-status/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/dariodumlijan/project-status/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/dariodumlijan/project-status/languages",
      "stargazers_url": "https://api.github.com/repos/dariodumlijan/project-status/stargazers",
      "contributors_url": "https://api.github.com/repos/dariodumlijan/project-status/contributors",
      "subscribers_url": "https://api.github.com/repos/dariodumlijan/project-status/subscribers",
      "subscription_url": "https://api.github.com/repos/dariodumlijan/project-status/subscription",
      "commits_url": "https://api.github.com/repos/dariodumlijan/project-status/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/dariodumlijan/project-status/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/dariodumlijan/project-status/contents/{+path}",
      "compare_url": "https://api.github.com/repos/dariodumlijan/project-status/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/dariodumlijan/project-status/merges",
      "archive_url": "https://api.github.com/repos/dariodumlijan/project-status/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/dariodumlijan/project-status/downloads",
      "issues_url": "https://api.github.com/repos/dariodumlijan/project-status/issues{/number}",
      "pulls_url": "https://api.github.com/repos/dariodumlijan/project-status/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/dariodumlijan/project-status/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/dariodumlijan/project-status/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/labels{/name}",
      "releases_url": "https://api.github.com/repos/dariodumlijan/project-status/releases{/id}",
      "deployments_url": "https://api.github.com/repos/dariodumlijan/project-status/deployments",
      "created_at": "2023-09-10T14:04:22Z",
      "updated_at": "2024-11-13T22:22:31Z",
      "pushed_at": "2024-11-13T22:18:04Z",
      "git_url": "git://github.com/dariodumlijan/project-status.git",
      "ssh_url": "git@github.com:dariodumlijan/project-status.git",
      "clone_url": "https://github.com/dariodumlijan/project-status.git",
      "svn_url": "https://github.com/dariodumlijan/project-status",
      "homepage": "https://project-status.dariodumlijan.com",
      "size": 1649,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": true,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": true,
      "web_commit_signoff_required": false,
      "topics": [
        "github-actions",
        "github-api",
        "github-pages",
        "react",
        "react-query",
        "reactjs",
        "scss",
        "status",
        "status-page",
        "typescript",
        "vite",
        "vitejs",
        "vitejs-react",
        "vitejs-react-typescript",
        "vitejs-template"
      ],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main",
      "permissions": {
        "admin": true,
        "maintain": true,
        "push": true,
        "triage": true,
        "pull": true
      }
    },
    "body": null,
    "reactions": {
      "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/14/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/14/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
  },
  {
    "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/15",
    "repository_url": "https://api.github.com/repos/dariodumlijan/project-status",
    "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/15/labels{/name}",
    "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/15/comments",
    "events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/15/events",
    "html_url": "https://github.com/dariodumlijan/project-status/issues/15",
    "id": 3147611234,
    "node_id": "I_kwDOKRtVu867nLxi",
    "number": 15,
    "title": "E-mail sending",
    "user": {
      "login": "dariodumlijan",
      "id": 79607795,
      "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dariodumlijan",
      "html_url": "https://github.com/dariodumlijan",
      "followers_url": "https://api.github.com/users/dariodumlijan/followers",
      "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
      "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
      "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
      "repos_url": "https://api.github.com/users/dariodumlijan/repos",
      "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "labels": [
      {
        "id": 8785596900,
        "node_id": "LA_kwDOKRtVu88AAAACC6mR5A",
        "url": "https://api.github.com/repos/dariodumlijan/project-status/labels/operational",
        "name": "operational",
        "color": "22c55e",
        "default": false,
        "description": ""
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2025-06-15T14:25:38Z",
    "updated_at": "2025-06-15T14:26:11Z",
    "closed_at": "2025-06-15T14:26:11Z",
    "author_association": "OWNER",
    "active_lock_reason": null,
    "sub_issues_summary": {
      "total": 0,
      "completed": 0,
      "percent_completed": 0
    },
    "repository": {
      "id": 689657275,
      "node_id": "R_kgDOKRtVuw",
      "name": "project-status",
      "full_name": "dariodumlijan/project-status",
      "private": false,
      "owner": {
        "login": "dariodumlijan",
        "id": 79607795,
        "node_id": "MDQ6VXNlcjc5NjA3Nzk1",
        "avatar_url": "https://avatars.githubusercontent.com/u/79607795?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dariodumlijan",
        "html_url": "https://github.com/dariodumlijan",
        "followers_url": "https://api.github.com/users/dariodumlijan/followers",
        "following_url": "https://api.github.com/users/dariodumlijan/following{/other_user}",
        "gists_url": "https://api.github.com/users/dariodumlijan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dariodumlijan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dariodumlijan/subscriptions",
        "organizations_url": "https://api.github.com/users/dariodumlijan/orgs",
        "repos_url": "https://api.github.com/users/dariodumlijan/repos",
        "events_url": "https://api.github.com/users/dariodumlijan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dariodumlijan/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/dariodumlijan/project-status",
      "description": "SPA (React) for displaying  project release notes & status using GitHub API",
      "fork": false,
      "url": "https://api.github.com/repos/dariodumlijan/project-status",
      "forks_url": "https://api.github.com/repos/dariodumlijan/project-status/forks",
      "keys_url": "https://api.github.com/repos/dariodumlijan/project-status/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/dariodumlijan/project-status/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/dariodumlijan/project-status/teams",
      "hooks_url": "https://api.github.com/repos/dariodumlijan/project-status/hooks",
      "issue_events_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/events{/number}",
      "events_url": "https://api.github.com/repos/dariodumlijan/project-status/events",
      "assignees_url": "https://api.github.com/repos/dariodumlijan/project-status/assignees{/user}",
      "branches_url": "https://api.github.com/repos/dariodumlijan/project-status/branches{/branch}",
      "tags_url": "https://api.github.com/repos/dariodumlijan/project-status/tags",
      "blobs_url": "https://api.github.com/repos/dariodumlijan/project-status/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/dariodumlijan/project-status/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/dariodumlijan/project-status/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/dariodumlijan/project-status/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/dariodumlijan/project-status/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/dariodumlijan/project-status/languages",
      "stargazers_url": "https://api.github.com/repos/dariodumlijan/project-status/stargazers",
      "contributors_url": "https://api.github.com/repos/dariodumlijan/project-status/contributors",
      "subscribers_url": "https://api.github.com/repos/dariodumlijan/project-status/subscribers",
      "subscription_url": "https://api.github.com/repos/dariodumlijan/project-status/subscription",
      "commits_url": "https://api.github.com/repos/dariodumlijan/project-status/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/dariodumlijan/project-status/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/dariodumlijan/project-status/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/dariodumlijan/project-status/contents/{+path}",
      "compare_url": "https://api.github.com/repos/dariodumlijan/project-status/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/dariodumlijan/project-status/merges",
      "archive_url": "https://api.github.com/repos/dariodumlijan/project-status/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/dariodumlijan/project-status/downloads",
      "issues_url": "https://api.github.com/repos/dariodumlijan/project-status/issues{/number}",
      "pulls_url": "https://api.github.com/repos/dariodumlijan/project-status/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/dariodumlijan/project-status/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/dariodumlijan/project-status/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/dariodumlijan/project-status/labels{/name}",
      "releases_url": "https://api.github.com/repos/dariodumlijan/project-status/releases{/id}",
      "deployments_url": "https://api.github.com/repos/dariodumlijan/project-status/deployments",
      "created_at": "2023-09-10T14:04:22Z",
      "updated_at": "2024-11-13T22:22:31Z",
      "pushed_at": "2024-11-13T22:18:04Z",
      "git_url": "git://github.com/dariodumlijan/project-status.git",
      "ssh_url": "git@github.com:dariodumlijan/project-status.git",
      "clone_url": "https://github.com/dariodumlijan/project-status.git",
      "svn_url": "https://github.com/dariodumlijan/project-status",
      "homepage": "https://project-status.dariodumlijan.com",
      "size": 1649,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": true,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": true,
      "web_commit_signoff_required": false,
      "topics": [
        "github-actions",
        "github-api",
        "github-pages",
        "react",
        "react-query",
        "reactjs",
        "scss",
        "status",
        "status-page",
        "typescript",
        "vite",
        "vitejs",
        "vitejs-react",
        "vitejs-react-typescript",
        "vitejs-template"
      ],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main",
      "permissions": {
        "admin": true,
        "maintain": true,
        "push": true,
        "triage": true,
        "pull": true
      }
    },
    "body": null,
    "reactions": {
      "url": "https://api.github.com/repos/dariodumlijan/project-status/issues/15/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dariodumlijan/project-status/issues/15/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
  }
];

export const getRoadmapResponse = {};