name: Test Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_call:
    secrets:
      access-token:
        required: false

env:
  NODE_VERSION: 20.0.0

jobs:
  run_tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run tests
      - run: yarn tsc
      - run: yarn lint
      - run: yarn test
