name: Test Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_call:
    secrets:
      access-token:
        required: false

env:
  NODE_VERSION: 20.0.0

jobs:
  run_tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      
      - name: Get yarn cache
        uses: actions/cache@v4
        id: cache # use this to check for `cache-hit` (`steps.cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies - Fresh
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Install dependencies - Cache
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn install --immutable

      # Run tests
      - run: yarn tsc
      - run: yarn lint
      - run: yarn test
